services:
  mars-rover-app-dev:
    build:
      context: .
      target: development
    container_name: mars-rover-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    networks:
      - mars-rover-network
    profiles:
      - dev

  mars-rover-app-prod:
    image: mars-rover-app:749da86
    container_name: mars-rover-app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - mars-rover-network
    profiles:
      - prod

networks:
  mars-rover-network:
    external: true
